# Generated by Django 4.1.7 on 2023-02-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_ordermodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='Drink', related_query_name='Drink', to='customer.menuitem'),
        ),
    ]
